apiVersion: v1
kind: Service
metadata:
  name: mbo-backend
  namespace: default
  labels:
    app: mbo-backend
spec:
  selector:
    app: mbo-backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mbo-frontend
  namespace: default
  labels:
    app: mbo-frontend
spec:
  selector:
    app: mbo-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mbo-reverse-proxy
  namespace: default
  labels:
    app: mbo-reverse-proxy
spec:
  selector:
    app: mbo-reverse-proxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP