apiVersion: v1
kind: Service
metadata:
  name: learnkitty-backend
  namespace: learnkitty
spec:
  selector:
    app: learnkitty-backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP