apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: media
  labels:
    app: jellyseerr
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      nodeSelector:
        kubernetes.io/hostname: nuclearbombcell-1
      containers:
      - image: fallenbagel/jellyseerr:latest
        name: jellyseerr
        volumeMounts:
        - name: config
          mountPath: /app/config
        ports:
        - containerPort: 5055
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 2048Mi
            ephemeral-storage: 1Gi
          requests:
            cpu: 25m
            memory: 1024Mi
      volumes:
      - name: config
        nfs:
            server: 192.168.1.215
            path: /meow/jellyseerr/config
            readOnly: false