apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden-cli
  labels:
    app: bitwarden-cli
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden-cli
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bitwarden-cli
    spec:
      containers:
      - image: ghcr.io/charlesthomas/bitwarden-cli:2025.6.1
        name: bitwarden-cli
        env:
          - name: BW_HOST
            value: "http://vaultwarden.default.svc.cluster.local"
          - name: BW_USER
            valueFrom:
              secretKeyRef:
                name: bitwarden-cli
                key: BW_USER
          - name: BW_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bitwarden-cli
                key: BW_PASSWORD
        ports:
        - containerPort: 8087
        resources:
          limits:
            cpu: "1"
            memory: 1024Mi
            ephemeral-storage: 64Mi
          requests:
            cpu: 512m
            memory: 16Mi