apiVersion: apps/v1
kind: Deployment
metadata:
  name: socials
  namespace: default
  labels:
    app: socials
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: socials
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: socials
    spec:
      containers:
      - image: ghcr.io/hiibolt/socials:latest
        name: socials
        ports:
        - containerPort: 4000 
          protocol: TCP        
        resources:
          limits:
            cpu: 5m
            memory: 64Mi
          requests:
            cpu: 2m
            memory: 32Mi