apiVersion: apps/v1
kind: Deployment
metadata:
  name: archi
  namespace: default
  labels:
    app: archi
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: archi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: archi
    spec:
      containers:
      - image: justarchi/archisteamfarm:6.1.6.4
        name: archi
        volumeMounts:
        - name: config
          mountPath: /app/config
     #  - name: plugins
     #     mountPath: /app/plugins
        ports:
        - containerPort: 1242 
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
            ephemeral-storage: 128Mi
          requests:
            cpu: 10m
      volumes:
      - name: config
        nfs:
         server: 192.168.1.203
         path: /mnt/meow/archi/config
     # - name: plugins
     #   nfs:
     #    server: 10.0.0.20
     #    path: /mnt/Pool1/ssd-storage/archi/plugins